{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sample-app.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "sample-app.name" . }}
{{- end }}
