# Profile: supply-chain (+ C1–C4)

stages:
  - validate
  - test
  - security
  - build
  - deploy

variables:
  REGISTRY: "${CI_REGISTRY_IMAGE}"
  SECURITY_POLICY: "config/security-gate-policy.yaml"
  ENABLE_REAL_LINTERS: "false"

include:
  - local: '/templates/gitlab/jobs/registry/variables.yml'
  - local: '/templates/gitlab/jobs/registry/login.yml'
  - local: '/templates/gitlab/jobs/_base.yml'
  - local: '/templates/gitlab/jobs/secret-scan.yml'
  - local: '/templates/gitlab/jobs/sast.yml'
  - local: '/templates/gitlab/jobs/osa.yml'
  - local: '/templates/gitlab/jobs/iac-scan.yml'
  - local: '/templates/gitlab/jobs/dockerfile-lint.yml'
  - local: '/templates/gitlab/jobs/linter-security.yml'
  - local: '/templates/gitlab/jobs/sbom.yml'
  - local: '/templates/gitlab/jobs/container-scan.yml'
  - local: '/templates/gitlab/jobs/sign.yml'
